name: Nightly Tests

on:
  schedule:
    - cron: '0 2 * * *'  # Run every day at 2 AM UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  nightly-regression:
    name: Nightly Regression Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-benchmark pytest-html
        
    - name: Run regression tests
      run: |
        pytest tests/ -v --tb=long \
          --html=regression-report.html --self-contained-html \
          --benchmark-only --benchmark-json=benchmark.json
          
    - name: Performance regression check
      run: |
        python -c "
        import json
        with open('benchmark.json', 'r') as f:
            data = json.load(f)
        # Add performance regression detection logic
        print('Performance check completed')
        "
        
    - name: Upload regression report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: nightly-regression-report
        path: |
          regression-report.html
          benchmark.json
          
    - name: Notify on failure
      if: failure()
      run: |
        echo "Nightly regression tests failed!"
        # Add notification logic